=== RaumZeit/nedit/doc/faq.dtd
<!--
  This DTD is based on QAML DTD. Modified by Florian Xhumari.
  $Id: faq.dtd,v 1.3 2002/09/26 12:37:37 ajhood Exp $
-->

<!ENTITY % text-styles 'email | img | site | link | em | strong | tt | code' >

<!ENTITY % paragraph-styles 'p | blockquote | ul | ol | pre' >


<!ELEMENT faq           (head, body) >

<!-- head -->

<!ELEMENT head          (title, version?, maintainers?, keywords*, summary?, download?)>

<!ELEMENT version       (#PCDATA) >
<!ELEMENT keywords		(#PCDATA) >
<!ELEMENT summary		(%paragraph-styles;)+ >
<!ELEMENT download		(%paragraph-styles;)+ >

<!-- body -->

<!ELEMENT body          (about-section?, (section+ | qna+)) >
<!ELEMENT about-section (title, (qna+ | q+ | (%paragraph-styles; | section)+)) >
<!ELEMENT section       (title, maintainers*, (qna+ | q+ | (%paragraph-styles; | section)+)) >
<!ELEMENT qna           (author?, q, long-q?, a+ )>
<!ELEMENT a             (contributor*, (%paragraph-styles;)+) >
<!ELEMENT q             (#PCDATA | %text-styles; )* >
<!ELEMENT long-q		(%paragraph-styles;)+ >

<!ELEMENT author        (name, email?) >
<!ELEMENT contributor   (name, email?) >

<!-- common for header and body -->

<!ELEMENT title         (#PCDATA) >
<!ELEMENT maintainers	(maintainer)+ >
<!ELEMENT maintainer    (name, email, subject?, address?) >

<!ELEMENT name          (#PCDATA) >
<!ELEMENT address       (#PCDATA) >
<!ELEMENT subject       (#PCDATA) >




<!-- text styles -->

<!ELEMENT email         (#PCDATA) >
<!ELEMENT img           EMPTY >
<!ELEMENT site			(#PCDATA) >
<!ELEMENT link          (#PCDATA) >

<!ELEMENT em            (#PCDATA) >
<!ELEMENT strong        (#PCDATA) >
<!ELEMENT tt            (#PCDATA) >
<!ELEMENT code          (#PCDATA) >


<!-- paragraph-like styles -->

<!ELEMENT blockquote	(p | ul | ol | pre | blockquote)+ >
<!ELEMENT p             (#PCDATA | %text-styles; )* >
<!ELEMENT ul            (li)+ >
<!ELEMENT ol            (li)+ >
<!ELEMENT li			(#PCDATA | %text-styles; )* >
<!ELEMENT pre			(#PCDATA) >




<!ATTLIST a             gist     CDATA   #IMPLIED >
<!ATTLIST about-section id       ID      #REQUIRED
                        gist     CDATA   #IMPLIED >
<!ATTLIST author        id       ID      #IMPLIED >
<!ATTLIST blockquote    id       ID      #IMPLIED >
<!ATTLIST contributor   id       ID      #IMPLIED >
<!ATTLIST faq           id       ID      #IMPLIED
                        xmlns:html CDATA #FIXED "http://www.w3.org/TR/REC-html40" >
<!ATTLIST img           src      CDATA   #REQUIRED
                        alt      CDATA   #IMPLIED >
<!ATTLIST link          href     CDATA   #REQUIRED
                        alt      CDATA   #IMPLIED >
<!ATTLIST maintainer    id       ID      #IMPLIED >
<!ATTLIST name          id       ID      #IMPLIED >
<!ATTLIST qna           id       ID      #REQUIRED
                        date     CDATA   #IMPLIED >
<!ATTLIST section       id       ID      #REQUIRED
                        gist     CDATA   #IMPLIED >

=== RaumZeit/nedit/doc/faq.xml
<?xml version="1.0"?>

<!DOCTYPE faq SYSTEM "faq.dtd" >

<!-- $Id: faq.xml,v 1.5 2002/12/13 17:20:25 edg Exp $ -->


<!--


A quick note on the syntax of this file 
========================================

This XML file is based on the DTD specified in "faq.dtd". See "faq.dtd" for
a rigourous definition; a simple overview is given here, to help in making
quick additions and modifications.

The FAQ is composed of two parts : a <head> and a <body>. The <head>
contains the title (in our case, "NEdit Frequently Asked Questions"), the
list of <maintainers>, a <summary> which gets displayed ahead of all
questions, a section showing how to download the FAQ (<download>) and
other, less important stuff.

The <body> part is composed of many FAQ <section>s. A section has a title
and groups several FAQ entries. A particular section exists, called
<about-section>, which contains the description of the FAQ itself.

A section is generally composed of several "Question 'N' Answer" entries
(<qna>). A <qna> contains a question (<q>) and the answer to that question
(<a>). An identifier must be given to each <qna>, via the attribute "id". A
longer version of the question may be specified via <long-q> as another
element of <qna>; in this case, the <q> is displayed in a table of
questions, while the longer and more complete version, <long-q>, is
displayed along with the answer.

The <long-q> and <a> elements contain text paragraphs. The <q> doesn't
contain paragraphs and behaves like a single paragraph itself.

A text paragraph is indicated by one of the elements <p>, <blockquote>,
<ul>, <ol> and <pre> (which, in the DTD, are collectively referred to as
%paragraph-styles;).

   The <p> denotes a basic paragraph and contains text.

   The <blockquote> indicates an indent, and it contains other paragraphs
   inside. A nested <blockquote> will indent relative to the previous one.

   The <ul> and <ol> indicate respectively an unnumbered and a numbered
   list. Both <ul> and <ol> contain one or many <li> elements. A <li>
   element contains text.

   The <pre> indicates a preformatted piece of text, which will be output
   with no further modifications.

Paragraphs of type <p> and <li>, as well as <q> and a few other elements of
the <head>, contain text. Text is composed of free text and style elements.
The style elements are the following :

   <email> indicates an e-mail address.
   
   <img> indicates an image. It has a required attribute "src" which must
   be a URL referring to the image, and a "alt" attribute containing
   alternate text, used for non-image-capable formats.

   <site> indicates a web site. The text between <site> and </site> must be
   a URL.

   <link> indicates a HTTP hyperlink. Its required attribute "href" must be
   the URL to link to. An attribute "alt" may contain alternate text.
   
   <em> stands for emphasized text.
   
   <strong> stands for strong text.
   
   <tt> is used for terminal output and for the contents of configuration
   files.

   <code> is used for command names, when included inline within text.
   Generally, <pre> paragraphs are used for several lines of code.

The distinction between <tt> and <code> and furthermore <pre> is not so
clear. A clearer and better definition is needed.



========================================

 -->


<faq>

<head>

<title>NEdit Frequently Asked Questions</title>

<version>2001/10/01</version>


<maintainers>
<!-- several maintainers can be added -->
<maintainer>
    <name>Florian Xhumari</name>
    <email>Florian.Xhumari@free.fr</email>
    <subject>NEdit FAQ</subject>
</maintainer>
</maintainers>

<summary>

<p>NEdit is a popular GUI-style text editor for Unix and VMS systems.
These are answers to the most frequently asked questions to
discuss@nedit.org. This information is also available from:</p>

<blockquote>
	<p><site>ftp://ftp.nedit.org/pub/</site>&lt;current&gt;/FAQ,</p>
</blockquote>

<p>and from the NEdit web page at:</p>

<blockquote>
	<p><site>http://nedit.org</site>.</p>
</blockquote>

</summary>

<download>
	<p>The FAQ is available for download in a variety of formats.</p>
	
	<ul>
		<li>HTML pages: <site>faq.tar.gz</site>
		or <site>faq.zip</site>.</li>
	
		<li>Plain text: <site>faq.txt</site>.</li>

		<li>XML source: <site>faq.xml</site>
	    as well as its DTD <site>faq.dtd</site>.</li>
	</ul>
	
</download>

</head>


<body>




    
<about-section id="about">
    <title>About the NEdit FAQ</title>
    
    <p>This FAQ is written in XML and translated to HTML using
    an XSL stylesheet. The XML source is processed using
    <link href="http://www.jclark.com/">James Clark's</link> XSLT processor
    <link href="http://www.jclark.com/xml/xt.html">XT</link> and
	XML parser <link href="http://www.jclark.com/xml/xp">XP</link>.
    </p>
    
	<p>The XSL stylesheet used to generate the HTML version is
	<link href="faq.xsl">here</link>.</p>
	
	<p>The text version is generated in three steps: first,
	<link href="faq-txt.xsl">an XSL	stylesheet</link>
	is used to generate a simple HTML. Then,
	<link href="faq-txt-pass2.xsl">a second XSL stylesheet</link> transforms
	the HTML into plain text.
	<link href="faq-txt.awk">An awk script</link>
	then performs the word wrapping.</p>
	    
    <p>For any questions about or contributions to the FAQ, please
    send a mail to the
    <link href="mailto:Florian.Xhumari@free.fr">maintainers</link>.
    </p>
</about-section>




<section id="sect_information">

<title>Where to get information</title>



<qna id="first-info">
<q>Where can I get information about NEdit?</q>

<a>

<p>The NEdit web page is at:</p>

<blockquote><p><site>http://nedit.org</site></p></blockquote>

<p>and it is mirrored in Australia at:</p>

<blockquote><p><site>http://www.au.nedit.org/</site></p></blockquote>


<p>The primary ftp site for NEdit is:</p>

<blockquote><p><site>ftp://ftp.nedit.org/pub</site></p></blockquote>

<p>which has a mirror in The Netherlands:</p>

<blockquote><p><site>ftp://ftp.nl.nedit.org/pub/mirror/NEdit</site></p></blockquote>


<p>The NEdit ftp site has executables for most Unix and VMS
systems, sources, documentation, and contributed software.</p>

<p>The first and easiest place to look for help with NEdit is the NEdit Help
menu.  The bottom item in the menu (Problems/Bugs) has answers to the most
commonly asked questions about NEdit, which are not duplicated here.  Also
check the platform specific information in the README file packaged in
the NEdit distribution kits.</p>

<p>If you have a problem that you really can't figure out, send mail
to <email>discuss@nedit.org</email>, and see if anyone else might be
having the same trouble.  The nedit developers also subscribe to this
list, and hopefully someone will be able to answer your question.
If you are a Silicon Graphics user and NEdit
came bundled on your system, you can also contact SGI's technical support.</p>

</a>
</qna>


<qna id="mailing-lists">
<q>Are there any mailing lists for NEdit users?</q>

<a>

<p>There are two separate mailing lists for nedit users, and one for
developers. Users may post to the developer mailing list to report
bugs and communicate with the nedit developers.</p>


<p>The lists are:</p>

<ul>

<li><email>discuss@nedit.org</email>: general discussion, questions and
answers among nedit users and developers.</li>

<li><email>develop@nedit.org</email>: communication among and with
nedit developers. Developers should also subscribe to the discuss
list.</li>

<li><email>announce@nedit.org</email>: a low-volume mailing list for
announcing new versions.</li>

</ul>

<p>Please note that only subscribers can send mail to the list. </p>

<p>The nedit developers subscribe to both
<email>discuss@nedit.org</email> and <email>develop@nedit.org</email>,
either of which may be used for reporting bugs. If you're not sure,
or you think the report might be of interest to the general nedit
user community, send the report to <email>discuss@nedit.org</email>. If it's
something obvious and boring, like we misspelled "anemometer" in the
on-line help, send it to <email>develop@nedit.org</email>.</p>

<p>Please do not cross post to both lists!</p>



<p>In order to subscribe to a list, send mail to <email>majordomo@nedit.org</email>
with one or more of the following in the body of the message:</p>

<pre>
    subscribe announce
    subscribe discuss
    subscribe develop
</pre>

<p>To unsubscribe do the same with the keyword <strong>unsubscribe</strong>.</p>

<pre>
    unsubscribe announce
    unsubscribe discuss
    unsubscribe develop
</pre>

<p>After subscribing, you will receive copies of all of the email
submitted to the lists. You may submit mail to the discussion list by
sending it to the appropriate list: <email>discuss@nedit.org</email>,
<email>develop@nedit.org</email> or
<email>announce@nedit.org</email>.</p>

<p>The archives of the old mailing lists (nedit_discuss@fnal_gov and
nedit_announce@fnal.gov) can be found on egroups.com:</p>

<blockquote>
	<ul>
	<li><site>http://www.egroups.com/group/nedit_discuss/</site></li>
    <li><site>http://www.egroups.com/group/nedit_announce/</site></li>
	</ul>
</blockquote>

<p>For more information about the mailing lists, refer to the <link
href="http://nedit.org/community/mailing.shtml">mailing lists
section</link> in the NEdit site.</p>


</a>
</qna>


<qna id="N44">
<q>Where can I get binaries / executables for machines other than
those available at NEdit site?</q>

<a>

<p>In past versions, we separated "supported" and "unsupported" executables
and divided them between the binary and contrib directories.  With more
supported systems, you're less likely to find executables in the contrib
directory, but it's worth a peek, anyhow.  If you can't find anything
appropriate, you can try asking in a usenet news group appropriate to your
system.  Other places to try are, the
<email>discuss@nedit.org</email> mailing list, or
<site>news:comp.windows.x.apps</site>
or <site>news:comp.editors</site>.</p>

</a>
